# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import stream_django.activity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, stream_django.activity.Activity),
        ),
    ]
