# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20160601_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
